**Numpy Basics**

1. Write a Numpy program to get the Numpy version and show the Numpy
build configuration.

In [ ]:
import numpy as np

numpy_version = np.__version__
print(f"NumPy Version: {numpy_version}")

numpy_build_config = np.show_config()
print("\nNumPy Build Configuration:")
print(numpy_build_config)

NumPy Version: 1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros 

2. Write a NumPy program to get help with the add function.


In [ ]:
import numpy as np
help_add = np.info(np.add)
print("Help for the add function:")
print(help_add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Write a NumPy program to test whether none of the elements of a given
array are zero.

In [ ]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
result = np.all(my_array != 0)
if result:
    print("None of the elements are zero.")
else:
    print("There is at least one zero element.")

None of the elements are zero.


4. Write a NumPy program to test if any of the elements of a given array are
non-zero.

In [ ]:
import numpy as np
my_array = np.array([0, 0, 3, 4, 0])
result = np.any(my_array != 0)
if result:
    print("At least one element is non-zero.")
else:
    print("All elements are zero.")

At least one element is non-zero.


5. Write a NumPy program to test a given array element-wise for finiteness
(not infinity or not a number).

In [ ]:
import numpy as np
my_array = np.array([1.0, np.inf, -np.inf, np.nan, 5.0])
result = np.isfinite(my_array)
print("Array Element-wise Finiteness Test:")
print(result)

Array Element-wise Finiteness Test:
[ True False False False  True]


6. Write a NumPy program to test elements-wise for positive or negative
infinity.

In [ ]:
import numpy as np
my_array = np.array([1.0, np.inf, -np.inf, np.nan, 5.0])
result = np.isinf(my_array)
print("Array Element-wise Infinity Test:")
print(result)

Array Element-wise Infinity Test:
[False  True  True False False]


7. Write a NumPy program to test element-wise for NaN of a given array.

In [ ]:
import numpy as np
my_array = np.array([1.0, np.inf, -np.inf, np.nan, 5.0])
result = np.isnan(my_array)
print("Array Element-wise NaN Test:")
print(result)

Array Element-wise NaN Test:
[False False False  True False]


8. Write a NumPy program to test element-wise for complex numbers, real
numbers in a given array. Also test if a given number is of a scalar type or
not.

In [ ]:
import numpy as np

my_array = np.array([1, 2.5, 3 + 4j, True, "hello"])
is_complex = np.iscomplexobj(my_array)
is_real = np.isrealobj(my_array)
number_to_check = 42
is_scalar = np.isscalar(number_to_check)
print("Array Element-wise Complex Test:")
print(is_complex)

print("\nArray Element-wise Real Test:")
print(is_real)

print("\nIs", number_to_check, "a scalar?")
print(is_scalar)

Array Element-wise Complex Test:
False

Array Element-wise Real Test:
True

Is 42 a scalar?
True


9. Write a NumPy program to test whether two arrays are element-wise equal
within a tolerance.


In [ ]:
import numpy as np
array1 = np.array([1.0, 2.0, 3.0])
array2 = np.array([1.0, 2.1, 3.0])
tolerance = 0.2
are_equal = np.allclose(array1, array2, atol=tolerance)
if are_equal:
    print("The arrays are element-wise equal within the tolerance.")
else:
    print("The arrays are not element-wise equal within the tolerance.")

The arrays are element-wise equal within the tolerance.


10. Write a NumPy program to create an element-wise comparison (greater,
greater_equal, less and less_equal) of two given arrays.


In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([2, 1, 3])

greater_than_result = np.greater(array1, array2)
greater_equal_result = np.greater_equal(array1, array2)

less_than_result = np.less(array1, array2)
less_equal_result = np.less_equal(array1, array2)

print("Array1 > Array2:", greater_than_result)
print("Array1 >= Array2:", greater_equal_result)
print("Array1 < Array2:", less_than_result)
print("Array1 <= Array2:", less_equal_result)

Array1 > Array2: [False  True False]
Array1 >= Array2: [False  True  True]
Array1 < Array2: [ True False False]
Array1 <= Array2: [ True False  True]


11. Write a NumPy program to create an element-wise comparison (equal,
equal within a tolerance) of two given arrays.


In [ ]:
import numpy as np
array1 = np.array([1.0, 2.0, 3.0])
array2 = np.array([1.1, 2.0, 3.0])
equal_result = np.equal(array1, array2)
tolerance = 0.2
equal_within_tolerance_result = np.allclose(array1, array2, atol=tolerance)
print("Element-wise Equality:", equal_result)
print("Element-wise Equality Within Tolerance:", equal_within_tolerance_result)

Element-wise Equality: [False  True  True]
Element-wise Equality Within Tolerance: True


12. Write a NumPy program to create an array with the values 1, 7, 13, 105
and determine the size of the memory occupied by the array.

In [ ]:
import numpy as np
my_array = np.array([1, 7, 13, 105])
memory_size = my_array.nbytes
print("Array:", my_array)
print("Memory Size:", memory_size, "bytes")

Array: [  1   7  13 105]
Memory Size: 32 bytes


13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10
fives.

In [ ]:
import numpy as np
zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = 5 * np.ones(10)
print("Array of 10 Zeros:", zeros_array)
print("Array of 10 Ones:", ones_array)
print("Array of 10 Fives:", fives_array)

Array of 10 Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 Ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 Fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


14. Write a NumPy program to create an array of integers from 30 to 70.

In [ ]:
import numpy as np
result_array = np.arange(30, 71)
print("Array of integers from 30 to 70:", result_array)

Array of integers from 30 to 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


15. Write a NumPy program to create an array of all even integers from 30 to
70.

In [ ]:
import numpy as np
even_array = np.arange(30, 71, 2)
print("Array of even integers from 30 to 70:", even_array)

Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


16. Write a NumPy program to create a 3x3 identity matrix.

In [ ]:
import numpy as np
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


17. Write a NumPy program to generate a random number between 0 and 1.


In [ ]:
import numpy as np
random_number = np.random.rand()
print("Random Number between 0 and 1:", random_number)

Random Number between 0 and 1: 0.6492632771895974


18. Write a NumPy program to generate an array of 15 random numbers from
a standard normal distribution.

In [ ]:
import numpy as np
random_numbers = np.random.randn(15)
print("Array of 15 random numbers from a standard normal distribution:")
print(random_numbers)

Array of 15 random numbers from a standard normal distribution:
[-0.70275479  0.01785472 -0.230647   -1.15270898 -0.6115683  -0.88461939
  1.33416747 -0.81236068  0.81740714 -1.26510747  0.84459954  0.73321586
  1.04324021  1.47999725  0.33573957]


19. Write a NumPy program to create a vector with values ranging from 15 to
55 and print all values except the first and last.

In [ ]:
import numpy as np
my_vector = np.arange(15, 56)
print("Original Vector:")
print(my_vector)
print("\nAll values except the first and last:")
print(my_vector[1:-1])

Original Vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]

All values except the first and last:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


20. Write a NumPy program to create a 3X4 array and iterate over it.


In [ ]:
import numpy as np
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
print("Iterating over the 3x4 array:")
for row in my_array:
    for element in row:
        print(element, end=" ")
    print()

Iterating over the 3x4 array:
1 2 3 4 
5 6 7 8 
9 10 11 12 


21. Write a NumPy program to create a vector of length 10 with values evenly
distributed between 5 and 50.


In [ ]:
import numpy as np
my_vector = np.linspace(5, 50, 10)
print("Vector with values evenly distributed between 5 and 50:")
print(my_vector)

Vector with values evenly distributed between 5 and 50:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


22. Write a NumPy program to create a vector with values from 0 to 20 and
change the sign of the numbers in the range from 9 to 15.

In [ ]:
import numpy as np
my_vector = np.arange(0, 21)
my_vector[9:16] *= -1
print("Vector with values from 0 to 20 and sign changed from 9 to 15:")
print(my_vector)

Vector with values from 0 to 20 and sign changed from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


23. Write a NumPy program to create a vector of length 5 filled with arbitrary
integers from 0 to 10.

In [ ]:
import numpy as np
random_vector = np.random.randint(0, 11, size=5)
print("Vector of length 5 with arbitrary integers from 0 to 10:")
print(random_vector)

Vector of length 5 with arbitrary integers from 0 to 10:
[ 4  7  5 10  1]


24. Write a NumPy program to multiply the values of two given vectors.


In [ ]:
import numpy as np
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
result_vector = vector1 * vector2
print("Result Vector (element-wise multiplication):")
print(result_vector)

Result Vector (element-wise multiplication):
[ 4 10 18]


25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [ ]:
import numpy as np
values = np.arange(10, 22)
matrix = values.reshape(3, 4)
print("3x4 Matrix filled with values from 10 to 21:")
print(matrix)

3x4 Matrix filled with values from 10 to 21:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
